name: Lint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Super-Linter
      uses: github/super-linter@v4
